cmd: don't double print error return by cmd.Execute
bbi's Execute() prints errors returned by cmd.Execute() to stdout, but
this leads to duplicate output because cobra's ExecuteC() already
prints the error to stderr (which is a more appropriate destination
than stdout).  For example:

  $ bbi nonmem reclean
  Error: must specify one positional argument, a directory
  Usage:
    bbi nonmem reclean [flags] <directory>
  [...]
  must specify one positional argument, a directory

Drop the Println() call from bbi's Execute() so that only the initial
error message (from cobra) is shown:

  Error: must specify one positional argument, a directory
  Usage:
    bbi nonmem reclean [flags] <directory>
  [...]